{% set data = load_setup_py_data() %}

package:
  name: psdm_qs_cli
  version: {{ data.get('version') }}

source:
  path : ..

build:
  number: 2
  noarch: python
  entry_points:
    - QSGenerateExcelSpreadSheet.py = psdm_qs_cli.QSGenerateExcelSpreadSheet:main
    - QSGenerateJSON.py = psdm_qs_cli.QSGenerateJSON:main

requirements:
  build:
    - python
    - pip
  run:
    - python
    - setuptools
    - krtc   # [not win]
    - requests
    - six

about:
  home: https://github.com/slaclab/psdm_qs_cli.git
  license: MIT License
