version: ~> 1.0

env:
  global:
    # TODO: psdm_qs_cli does not currently have any built documentation.
    # doctr generated secure variable for documentation upload
    # - secure: "<your secure here>"
   
    # enable the usage of versions menu which allow versioning of the docs
    # pages and not only the master branch
    - DOCTR_VERSIONS_MENU="1"
    # Dependency files used to build the documentation (space separated)
    - DOCS_REQUIREMENTS="dev-requirements.txt requirements.txt"

    # Options to be passed to flake8 for package linting. Usually this is just
    # the package name but you can enable other flake8 options via this config
    - PYTHON_LINT_OPTIONS="psdm_qs_cli"

    # The name of the conda package
    - CONDA_PACKAGE="psdm_qs_cli"
    # The folder containing the conda recipe (meta.yaml)
    - CONDA_RECIPE_FOLDER="conda-recipe"
    # Extra dependencies needed to run the tests which are not included
    # at the recipe and dev-requirements.txt. E.g. PyQt
    - CONDA_EXTRAS="pip"
    # Requirements file with contents for tests dependencies
    - CONDA_REQUIREMENTS="dev-requirements.txt"

    # Extra dependencies needed to run the test with Pip (similar to
    # CONDA_EXTRAS) but for pip
    - PIP_EXTRAS=""

# Uncomment this block if you would like to make the Python PIP test an allowed
# failure
#jobs:
#  allow_failures:
#    # This makes the PIP based Python 3.6 optional for passing.
#    # Remove this block if passing tests with PIP is mandatory for your
#    # package
#    - name: "Python 3.6 - PIP"

# If not using the standard-python-conda above please uncomment the required
# (language, os, dist and stages) and optional (import statements) entries from
# the blocks below.
#
language: python
os: linux
dist: xenial

stages:
  - build
  - test
  - name: deploy
    if: (branch = master OR tag IS present) AND type != pull_request

import:
  # Build Stage
  - pcdshub/pcds-ci-helpers:travis/shared_configs/anaconda-build.yml
  - pcdshub/pcds-ci-helpers:travis/shared_configs/python-tester-pip.yml
  # Tests Stage
  - pcdshub/pcds-ci-helpers:travis/shared_configs/python-tester-conda.yml
  - pcdshub/pcds-ci-helpers:travis/shared_configs/python-linter.yml
  - pcdshub/pcds-ci-helpers:travis/shared_configs/package-linter.yml
  - pcdshub/pcds-ci-helpers:travis/shared_configs/docs-build.yml
  # Deploy Stage
  - pcdshub/pcds-ci-helpers:travis/shared_configs/pypi-upload.yml
  # Skip docs:
  # - pcdshub/pcds-ci-helpers:travis/shared_configs/doctr-upload.yml
  - pcdshub/pcds-ci-helpers:travis/shared_configs/anaconda-upload.yml
